DROP TABLE IF EXISTS todos CASCADE;
CREATE TABLE todos (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  created_at DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  priority INTEGER NOT NULL DEFAULT 1,
  complete BOOLEAN NOT NULL DEFAULT FALSE,
  todo_id INTEGER REFERENCES todos(id),
  category_id INTEGER REFERENCES categories(id) ON DELETE CASCADE NOT NULL
);